data_sets_jakob:
  - Adiac
  - Beef
  - BeetleFly
  - BirdChicken
  - ChlorineConc
  - Computers
  - CricketY
  - Crop
  - Earthquakes
  - ECG200
  - ECG5000
  - ElectricDevices
  - Haptics
  - Herring
  - InlineSkate
  - Lightning2
  - Lightning7
  - MidPhalOutAgGrp
  - MidPhalTW
  - MoteStrain
  - OliveOil
  - OSULeaf
  - Phoneme
  - ScreenType
  - ShapesAll
  - SmallKitchenApp
  - UWaveGestLibAll
  - Wine
  - WordSynonyms
  - Worms